### ISSUE TITLE
javascript evaluation

### ISSUE THREAD

**Issue by HosseinAlipour** [gajus/surgeon#24]
the page I want to scrape uses Api to get content. is javascript evaluation possible in the page? how do i connect this to Phantomjs or Puppeteer?

**Comment by gajus** [comment]
There is a browser evaluator that you can use to evaluate Surgeon in a browser.

https://github.com/gajus/surgeon#browser-evaluator

Surgeon itself does not deal with evaluation of scripts. Surgeon only works with the given DOM tree.

**Comment by HosseinAlipour** [comment]
So, How do I run the browser evaluator on Puppeteer?
Sorry, for me, the documentation wasn't clear enough.

**Comment by gajus** [comment]
The linked example gives all the code to initialize Surgeon in a browser environment.

```js
import {
  browserEvaluator
} from './evaluators';

surgeon({
  evaluator: browserEvaluator()
});

```

**Comment by drundanibel** [comment]
Sorry, I'm facing the same challenge and don't quite understand how I can use this code snippet to interact with Puppeteer. To make it concrete, with pure Puppeteer I would write something like this:

const titles = await page.evaluate(() =>
    Array.from(document.querySelectorAll('h1.title')))
      .map(titles => titles.innerText.trim())
    )

How do I bring this together with your code snippet above?
