### ISSUE TITLE
Make syntax engine selectable like evaluator is

### ISSUE THREAD

**Issue by ComLock** [gajus/surgeon#33]
Pianola is great and does it's thing, but what if you want to roll your own syntax engine. Not that I have one ready.

**Comment by gajus** [comment]
I suggest raising a suggestion for syntax additions to Pianola first.

The argument would be similar to what is being advocated in this article:

https://blog.timescale.com/sql-vs-flux-influxdb-query-language-time-series-database-290977a01a8a

tl;dr; learning/ adding new pattern is going to be easier than inventing a wheel; you benefit from community support.
