### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by ali-habibzadeh** [gajus/surgeon#34]
Any plans to add types?  These days it is pretty much expected out of the box.

**Comment by gajus** [comment]
No.

**Comment by gajus** [comment]
To elaborate: Strict types don't make much sense in the context of a data extraction tool with a custom DSL – types cannot tell you neither what are the required inputs or required outputs.

We might have a use case for Flow, as Flow supports runtime annotations (via https://github.com/gajus/flow-runtime), but I am struggling to see the benefit at this point.

**Comment by NSExceptional** [comment]
@gajus Please add typescript support. You don't have to use strict types for results, that is what `any`/`unknown` are for. We just need typings for method signatures and such. It looks like you're already [using them yourself](https://github.com/gajus/surgeon/blob/master/src/types.js) (in JS, somehow? news to me) so I don't know why you're so against this 😕
