### ISSUE TITLE
Friendly aliases

### ISSUE THREAD

**Issue by insideone** [gajus/surgeon#36]
rtc is a short alias, but isn't friendly. So are all of them.

How about such additional aliases:

Current | Additional | Description
-- | -- | --
ra | attr | Reads Element attribute value
rdtc | text | Removes any descending elements and reads the resulting textContent property of an element
rih | html | Reads innerHTML property of an element
roh | outerHtml | Reads outerHTML property of an element
rp | prop | Reads Element property value
rtc | allText | Reads textContent property of an element
sa | all | Select any (sa). Selects multiple elements (0 or more). Returns array
sm | many | Select many (sm). Selects multiple elements (1 or more). Returns array
smo | firstOrNull | Select maybe one (smo). Selects one element. Returns single result or null
saf | - | ...
so | first | Select one (so). Selects a single element. Returns single result

Still short, but easier to remember

wdyt?

**Comment by gajus** [comment]
`saf` select any first. So, if you do `saf .date` and there are 0 or many elements matching that selector, it will select `null` or the first element.

**Comment by gajus** [comment]
either way, it is simple to create your own alias preset. Not planning to update the built-in preset. It has been adopted and in use across many projects.
