### ISSUE TITLE
Request to add a tutorial / how to use

### ISSUE THREAD

**Issue by LonelyDaoist** [gajus/surgeon#37]
Greetings, I was looking for other way to scrape websites with puppeteer because it was too slow and I came across this [article](https://medium.com/@gajus/it-is-a-really-silly-idea-to-use-puppeteer-to-scrape-the-web-da62a9f3de7e). However the problem is that I can't seem to find any tutorial or guide that would help me set things up and running fast since I don't have much time, also the Readme isn't really that clear.

Thank you

**Comment by gajus** [comment]
Documentation already covers it.
