### ISSUE TITLE
Add a command line interface to surgeon in the spirit of jq?

### ISSUE THREAD

**Issue by ts709** [gajus/surgeon#40]
jq (https://github.com/stedolan/jq) is a powerful command line json parser. I see that surgeon provides a similar function for html. I am aware that there are a few html command line parsers inspired by jq, for example pup (https://github.com/ericchiang/pup), but from what I can see they are less powerful than surgeon. My suggestion is to add a command line interface to surgeon.

**Comment by gajus** [comment]
This sounds like a good fit for https://github.com/gajus/surgeon#user-defined-subroutines

It is pretty straightforward to extend Surgeon with custom subroutines such as jq.

I suggest try it out this way, and if you find that it is particularly useful, then contribute back to Surgeon codebase.
